### ISSUE TITLE
 installation problem

### ISSUE THREAD

**Issue by gitmet** [vinc96/Multi-Highlight#1]
how to install it?

**Comment by vinc96** [comment]
Hi, it is just like much other chrome extension repositories. You can do the following:
1. Download the [repository](https://github.com/vinc96/Multi-Highlight/archive/master.zip), unzip the zip file.
2. Open [chrome extensions manager](chrome://extensions/), click the "Load unpacked" at the top left corner, and select the unzipped folder "Multi-Highlight-master" in the popup window.

**Comment by gitmet** [comment]
Thank you, it works.

**Comment by vinc96** [comment]
NP
