### ISSUE TITLE
How to make it work defaulted for every sites just like the other Multi-Highlight extension?

### ISSUE THREAD

**Issue by Engiun** [vinc96/Multi-Highlight#2]
Thanks very much for your perfect work~
I think this extension is better than  the other Multi-Highlight extension because I don't use English and this one can highlight the single letter words in my language(Chinese).
But I want to make it work defaulted for every sites and save the keywords, don't need the shortkey to active it. How can i do it ?

**Comment by vinc96** [comment]
Hi, I am glad that you like this extension.

Do you mean to apply the same keywords across all existing tabs? In other words, highlight the same keywords in all opened websites?
Maybe you could provide me a similar extension that has your desired behavior. I will analysis it and consider adding that feature soon.

Thanks

**Comment by Engiun** [comment]
Yes, You've got my thought!

I want a choosable feature that highlights the same keywords in all opened websites and works instantlly when i open a tab without pressing the shortkey to active the highlights, just like this extension [https://chrome.google.com/webstore/detail/multi-highlight/pfgfgjlejbbpfmcfjhdmikihihddeeji](url)

I'm sorry my English's poor, hope you can understand it. Many thanks !

**Comment by vinc96** [comment]
I added a "paste keywords in new pages" features.
With its enabled, the latest keywords will be pasted to the new pages you open.
Though this new feature might not be as foolproof as the one you mentioned in the link, it takes care of users who don't want the latest keywords to override previous keywords.

Thanks.

**Comment by vinc96** [comment]
I have submitted the new version to Chrome Web Store. It should be available in one week.
You can test it out by downloading the code from this repository and install using the "load unpacked" button at chrome://extensions/

**Comment by vinc96** [comment]
I added a "paste keywords to new pages" features.
With its enabled, the latest keywords will be pasted to the new pages you open (or refresh page).
Though this new feature might not be as foolproof as the one you mentioned in the link, it takes care of users who don't want the latest keywords to override previous keywords.

I have submitted the new version to Chrome Web Store. It should be available in one week.
You can test it out by downloading the code from this repository and install using the "load unpacked" button at chrome://extensions/

Would you mind to share me why you need such a feature? So I can make this extension more general.

Thanks.

**Comment by vinc96** [comment]
I added a "paste keywords to new pages" features.
With its enabled, the latest keywords will be pasted to the new pages you open (or refresh page).
Though this new feature might not be as foolproof as the one you mentioned in the link, it takes care of users who don't want the latest keywords to override previous keywords.

I have submitted the new version to Chrome Web Store. It should be available in one week.
You can test it out by downloading the code from this repository and install using the "load unpacked" button at chrome://extensions/

Thanks.

**Comment by Engiun** [comment]
Thanks very much for your work！
Maybe you can consider the function of keywords grouping and saving the configs of group for each site. Just a little suggestion for you to consider~

**Comment by vinc96** [comment]
Thanks. Nice suggestion. I will implement it if more users require it :-)
