### ISSUE TITLE
The interface is not visible

### ISSUE THREAD

**Issue by lhj5426** [vinc96/Multi-Highlight#4]
![image](https://user-images.githubusercontent.com/30548000/67228901-cf1de900-f46c-11e9-851f-e92f5461958a.png)
 Delimiter
,
What delimiter to separate your keywords? 

The interface is not visible

![image](https://user-images.githubusercontent.com/30548000/67230474-f1fdcc80-f46f-11e9-9fbc-ab5a99ce79b1.png)

The fill in interface of separator will be displayed correctly after the text is shortened.

Please optimize the pop-up interface

**Comment by vinc96** [comment]
Hi Ihj5426,
I am not able to reproduce this bug on my device.
![20191021capture](https://user-images.githubusercontent.com/11984137/67229816-4fa30200-f3f9-11e9-9f1e-b7521c74cfda.jpg)

Can reinstalling the extension solve the problem?
If you know any probable cause, I will look into that.

Thanks,

**Comment by lhj5426** [comment]
Reinstall problem window problem still exists
I changed to another language and shortened the position of the text on the pop-up window to display the separator space correctly.

Can you also set custom colors
![image](https://user-images.githubusercontent.com/30548000/67230881-bdd6db80-f470-11e9-9eb3-7577033b4f06.png)

**Comment by vinc96** [comment]
Thanks for your helpful information. I will do that when I get time.

Seems like you know the code of this extension. Would you mind to pull request your desired changes (e.g. custom colours)? I will integrate your changes into the extension accordingly.

**Comment by lhj5426** [comment]
If you customize the color of the keyword in the settings, of course, it is better... now the default 7 keywords 7 colors, I changed the code to 20 keywords 20 colors, I think I like the custom keyword color  Users should still have 😋

**Comment by vinc96** [comment]
I see, thanks :-)

**Comment by vinc96** [comment]
The bug should be fixed. Now size of the popup window is also customizable.
